Logging:
    default: INFO

General:
    Modus:          Collider
    Time_Step_Mode: Fixed
    Delta_Time:     0.2
    End_Time:       30.0
    Randomseed:     -1
    Nevents:        1

Output:
    Initial_Conditions:
      Format: ["Oscar2013"]
      Extended: True
    Particles:
      Format: ["Oscar2013"]
      Extended: True
#      Only_Final: "Yes"
#    Thermodynamics:
#      Format: ["Lattice_ASCII"]
#      Type: "hadron"
#      Quantities: ["tmn"]
#    Output_Interval: 1
#
#Lattice:
#    Automatic: false
#    Origin: [-40.0, -40.0, -40.0]
#    Sizes: [80.0, 80.0, 80.0]
#    Cell_Number: [100, 100, 100]

Modi:
    Collider:
        Projectile:
            Particles: {2212: 79, 2112: 118} #Gold197
        Target:
            Particles: {2212: 79, 2112: 118} #Gold197
        Sqrtsnn: ENERGY
        Fermi_Motion: frozen
        Initial_Conditions:
            Type: "Dynamic"
            Energy_Density_Threshold: THRESHOLD
            Maximum_3Momentum: MAX_3MOM
            Formation_Time_Fraction: FLUID_TIME

Collision_Term:
    Force_Decays_At_End: false
